const pool = require('./src/config/db');

const ndcCards = [
  {"front": "What is Cisco IOS?", "back": "Internetwork Operating System used on Cisco devices"},
  {"front": "Where is the IOS stored on a Cisco device?", "back": "Flash memory"},
  {"front": "Where is the running-config stored?", "back": "RAM"},
  {"front": "Where is the startup-config stored?", "back": "NVRAM"},
  {"front": "What is the default mode when first accessing a Cisco device?", "back": "User EXEC mode"},
  {"front": "What is the prompt for Privileged EXEC mode?", "back": "Router#"},
  {"front": "What command enters Privileged EXEC mode?", "back": "enable"},
  {"front": "What command enters Global Configuration mode?", "back": "configure terminal"},
  {"front": "What is the purpose of the console port?", "back": "Provides out-of-band access for initial configuration and recovery"},
  {"front": "What is the difference between Telnet and SSH?", "back": "SSH is encrypted and secure; Telnet sends data in plaintext"},
  {"front": "Which memory on a Cisco device is non-volatile and stores the startup configuration?", "back": "NVRAM"},
  {"front": "What does RAM on a Cisco router store?", "back": "Running IOS, running-config, routing tables, and packet buffers"},
  {"front": "What is a VLAN?", "back": "A logical broadcast domain that groups hosts regardless of physical location"},
  {"front": "What is the default VLAN on a Cisco switch?", "back": "VLAN 1"},
  {"front": "What is a trunk port?", "back": "A port that carries traffic for multiple VLANs"},
  {"front": "What is the difference between an access port and a trunk port?", "back": "Access port carries one VLAN; trunk port carries multiple VLANs"},
  {"front": "What is the 802.1Q standard?", "back": "A frame tagging protocol for VLANs"},
  {"front": "What is the native VLAN?", "back": "The VLAN that carries untagged traffic on a trunk"},
  {"front": "What command creates a VLAN?", "back": "vlan vlan_number"},
  {"front": "What command assigns a port to a VLAN?", "back": "switchport access vlan vlan_number"},
  {"front": "What is VTP?", "back": "VLAN Trunking Protocol - manages VLAN configurations across switches"},
  {"front": "What are the three VTP modes?", "back": "Server, Client, and Transparent"},
  {"front": "What is the default VTP mode?", "back": "Server"},
  {"front": "What is STP?", "back": "Spanning Tree Protocol - prevents switching loops"},
  {"front": "What is the root bridge in STP?", "back": "The switch with the lowest bridge ID that is the focal point of the STP topology"},
  {"front": "What is a BPDU?", "back": "Bridge Protocol Data Unit - frames exchanged by switches for STP"},
  {"front": "What are the four STP port states?", "back": "Blocking, Listening, Learning, and Forwarding"},
  {"front": "What is a designated port in STP?", "back": "A port that forwards traffic toward the root bridge but is not the root port"},
  {"front": "What is a blocked port in STP?", "back": "A port that does not forward traffic to prevent loops"},
  {"front": "What is a root port in STP?", "back": "The port with the least cost path back to the root bridge"},
  {"front": "What is the default STP bridge priority?", "back": "32768"},
  {"front": "What is a routing protocol?", "back": "A protocol that dynamically shares routing information between routers"},
  {"front": "What is the difference between static and dynamic routing?", "back": "Static routes are manually configured; dynamic routes are learned automatically"},
  {"front": "What is a metric in routing?", "back": "A value used to determine the best path to a destination network"},
  {"front": "What metric does RIP use?", "back": "Hop count"},
  {"front": "What is the maximum hop count for RIP?", "back": "15 hops"},
  {"front": "What is the administrative distance of RIP?", "back": "120"},
  {"front": "What is the administrative distance of EIGRP?", "back": "90"},
  {"front": "What is the administrative distance of OSPF?", "back": "110"},
  {"front": "What does AD measure in routing?", "back": "Trustworthiness of a route source (lower is better)"},
  {"front": "What is the difference between RIPv1 and RIPv2?", "back": "RIPv2 supports VLSM and sends subnet masks in updates; RIPv1 is classful"},
  {"front": "What is EIGRP?", "back": "Enhanced Interior Gateway Routing Protocol - Cisco proprietary distance vector protocol"},
  {"front": "What algorithm does EIGRP use?", "back": "DUAL (Diffusing Update Algorithm)"},
  {"front": "What are the three tables maintained by EIGRP?", "back": "Neighbor table, Topology table, Routing table"},
  {"front": "What is OSPF?", "back": "Open Shortest Path First - a link-state routing protocol"},
  {"front": "What algorithm does OSPF use?", "back": "Dijkstra's SPF algorithm"},
  {"front": "What is Area 0 in OSPF?", "back": "The backbone area to which all other areas must connect"},
  {"front": "What is a DR in OSPF?", "back": "Designated Router - reduces updates on multi-access networks"},
  {"front": "What is a BDR in OSPF?", "back": "Backup Designated Router - takes over if DR fails"},
  {"front": "What is BGP?", "back": "Border Gateway Protocol - an exterior routing protocol"},
  {"front": "What is NAT?", "back": "Network Address Translation - translates private to public addresses"},
  {"front": "What are the private IP address ranges?", "back": "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"},
  {"front": "What is the difference between static NAT and dynamic NAT?", "back": "Static NAT has a fixed 1:1 mapping; dynamic NAT uses a pool of addresses"},
  {"front": "What is PAT?", "back": "Port Address Translation - also known as NAT Overload"},
  {"front": "What is the difference between NAT and PAT?", "back": "NAT maps IP to IP; PAT maps multiple IPs to a single IP using different ports"},
  {"front": "What is an ACL?", "back": "Access Control List - a set of rules that filter network traffic"},
  {"front": "What is the difference between standard and extended ACLs?", "back": "Standard ACLs filter by source IP only; Extended ACLs filter by source, destination, protocol, and port"},
  {"front": "What are the standard ACL number ranges?", "back": "1-99 and 1300-1999"},
  {"front": "What are the extended ACL number ranges?", "back": "100-199 and 2000-2699"},
  {"front": "What is the implicit deny in ACLs?", "back": "An invisible rule that denies all traffic not explicitly permitted"},
  {"front": "What is port security?", "back": "Limits the MAC addresses allowed on a switch port"},
  {"front": "What are the three port security violation modes?", "back": "Protect, Restrict, and Shutdown"},
  {"front": "What is the default port security violation mode?", "back": "Shutdown"},
  {"front": "What is DHCP?", "back": "Dynamic Host Configuration Protocol - automatically assigns IP addresses"},
  {"front": "What are the three DHCP address allocation methods?", "back": "Manual, Automatic, and Dynamic"},
  {"front": "What is a default route?", "back": "A route used when no specific route matches the destination"},
  {"front": "What is a stub network?", "back": "A network accessed by only one route"},
  {"front": "What is load balancing in routing?", "back": "Using multiple equal-cost paths to forward traffic"},
  {"front": "What is convergence in routing?", "back": "When all routers have consistent routing information"},
  {"front": "What is the purpose of the AUX port?", "back": "Remote access via dial-up connection"},
  {"front": "What is the difference between a hub and a switch?", "back": "Hub broadcasts to all ports; Switch forwards based on MAC addresses"},
  {"front": "What is the difference between a bridge and a switch?", "back": "A bridge has fewer ports; switches have more ports and higher performance"},
  {"front": "What is a router?", "back": "A device that forwards packets between networks"},
  {"front": "What is a gateway?", "back": "A device that connects networks with different protocols"},
  {"front": "What is a wireless AP?", "back": "Access Point - device that connects wireless clients to a wired network"},
  {"front": "What is SSID?", "back": "Service Set Identifier - the name of a WLAN"},
  {"front": "What is the difference between WEP and WPA?", "back": "WPA is more secure with dynamic keys; WEP has static keys"},
  {"front": "What is MAC filtering?", "back": "Allowing only specific MAC addresses to connect to a wireless network"},
  {"front": "What is the difference between open and PSK authentication on WLAN?", "back": "Open has no authentication; PSK uses a pre-shared key"},
  {"front": "What is the Spanning Tree root bridge election based on?", "back": "The lowest bridge ID"},
  {"front": "What is the difference between distance vector and link-state routing?", "back": "Distance vector shares entire tables; link-state shares topology information"},
  {"front": "What is DLCI in Frame Relay?", "back": "Data Link Connection Identifier - identifies virtual circuits"},
  {"front": "What is PPP?", "back": "Point-to-Point Protocol - used for WAN connections"},
  {"front": "What is the difference between PAP and CHAP?", "back": "CHAP uses three-way handshake and is more secure; PAP sends password in plaintext"},
  {"front": "What is the command to encrypt passwords in the configuration?", "back": "service password-encryption"},
  {"front": "What is the command to set a banner on a Cisco device?", "back": "banner motd"},
  {"front": "What is the command to save the running config to startup config?", "back": "copy running-config startup-config"},
  {"front": "What does the command 'no shutdown' do on an interface?", "back": "Enables the interface"},
  {"front": "What command displays the routing table?", "back": "show ip route"},
  {"front": "What command displays the interface status?", "back": "show ip interface brief"},
  {"front": "What is a subinterface?", "back": "A logical subdivision of a physical interface used for inter-VLAN routing"},
  {"front": "What is router-on-a-stick?", "back": "A configuration using subinterfaces for inter-VLAN routing"},
  {"front": "What is VLSM?", "back": "Variable Length Subnet Mask - allows subnets of different sizes"},
  {"front": "What is the command to configure a static route?", "back": "ip route destination_network subnet_mask next_hop"},
  {"front": "What does the 'passive-interface' command do?", "back": "Disables routing updates on an interface"},
  {"front": "What is Frame Relay?", "back": "A WAN technology that uses virtual circuits"},
  {"front": "What command verifies trunk configuration?", "back": "show interface trunk"},
  {"front": "What is the default VTP version?", "back": "Version 1"},
  {"front": "What is the hello interval for STP?", "back": "2 seconds"},
  {"front": "What is the maximum age timer in STP?", "back": "20 seconds"},
  {"front": "What is the command to disable VTP pruning?", "back": "vtp pruning"},
  {"front": "What is the purpose of the 'ip helper-address' command?", "back": "Forwards DHCP broadcasts to a DHCP server"}
];

const ip2Cards = [
  {"front": "What does PHP stand for?", "back": "Hypertext Preprocessor"},
  {"front": "What is a server-side scripting language?", "back": "A language executed on the web server to generate dynamic web pages"},
  {"front": "What is the default file extension for PHP files?", "back": ".php"},
  {"front": "What are the three vital components needed to run PHP?", "back": "Web server, PHP parser, Database"},
  {"front": "What is the difference between echo and print in PHP?", "back": "echo has no return value; print returns 1"},
  {"front": "What is the correct way to start and end a PHP code block?", "back": "<?php ... ?>"},
  {"front": "What is the superglobal used to access form data sent via POST method?", "back": "$_POST"},
  {"front": "What is the superglobal used to access form data sent via GET method?", "back": "$_GET"},
  {"front": "What is the superglobal used to access session variables?", "back": "$_SESSION"},
  {"front": "What is the superglobal used to access cookie data?", "back": "$_COOKIE"},
  {"front": "What is the superglobal used to access server environment variables?", "back": "$_SERVER"},
  {"front": "What does session_start() do?", "back": "Starts a new session or resumes an existing session"},
  {"front": "How do you create a cookie in PHP?", "back": "Using the setcookie() function"},
  {"front": "What is the difference between sessions and cookies?", "back": "Sessions are stored on the server; cookies are stored on the client side"},
  {"front": "What is the function to destroy a session in PHP?", "back": "session_destroy()"},
  {"front": "What is the purpose of the header() function in PHP?", "back": "Sends a raw HTTP header to the client"},
  {"front": "What is the difference between include and require in PHP?", "back": "require causes fatal error if file not found; include only gives a warning"},
  {"front": "What is the difference between include_once and include?", "back": "include_once includes the file only once"},
  {"front": "What is the purpose of the $GLOBALS superglobal?", "back": "Access all global variables"},
  {"front": "What is the difference between double quotes and single quotes in PHP?", "back": "Double quotes parse variables; single quotes treat as literal string"},
  {"front": "What is the output of echo 'Hello $name' if $name = 'John'?", "back": "Hello $name (single quotes don't parse variables)"},
  {"front": "What is the output of echo \"Hello $name\" if $name = 'John'?", "back": "Hello John"},
  {"front": "What is the purpose of the empty() function in PHP?", "back": "Checks if a variable is empty"},
  {"front": "What is the purpose of the isset() function in PHP?", "back": "Checks if a variable is set and not NULL"},
  {"front": "What is the mysqli extension?", "back": "Improved MySQL extension for PHP"},
  {"front": "What is the difference between mysqli and PDO?", "back": "mysqli only works with MySQL; PDO works with multiple databases"},
  {"front": "What is the purpose of prepared statements?", "back": "To prevent SQL injection by separating query logic from data"},
  {"front": "What is the purpose of htmlspecialchars() in PHP?", "back": "Converts special characters to HTML entities to prevent XSS"},
  {"front": "What is the purpose of password_hash() in PHP?", "back": "Creates a secure hash of a password"},
  {"front": "What algorithm does password_hash() use by default?", "back": "bcrypt"},
  {"front": "What is the purpose of the filter_var() function?", "back": "Validates and sanitizes data"},
  {"front": "What is the output of echo 10 + '10 apples' in PHP?", "back": "20 (PHP converts string to number)"},
  {"front": "What are the three types of arrays in PHP?", "back": "Indexed, Associative, Multidimensional"},
  {"front": "How do you add an element to an array in PHP?", "back": "$array[] = 'value' or array_push()"},
  {"front": "What is the difference between array_merge() and + operator for arrays?", "back": "array_merge() reindexes; + keeps first array keys"},
  {"front": "What is a namespace in PHP?", "back": "A way to encapsulate items to avoid name collisions"},
  {"front": "What is the difference between const and define() in PHP?", "back": "const is compile-time; define() is runtime. const works in classes"},
  {"front": "What is the purpose of the use keyword in PHP?", "back": "Imports classes, functions, or constants from a namespace"},
  {"front": "What is a trait in PHP?", "back": "A mechanism for code reuse in single inheritance languages like PHP"},
  {"front": "What is the difference between abstract class and interface in PHP?", "back": "Abstract class can have method implementations; interface cannot"},
  {"front": "What is the purpose of the __construct() method in PHP?", "back": "The class constructor, called when an object is created"},
  {"front": "What is the purpose of the __destruct() method?", "back": "Called when an object is destroyed"},
  {"front": "What is the purpose of the __call() magic method?", "back": "Handles calls to undefined methods"},
  {"front": "What is the purpose of the __get() magic method?", "back": "Handles reading undefined properties"},
  {"front": "What is the purpose of the __set() magic method?", "back": "Handles writing to undefined properties"},
  {"front": "What is the purpose of the __toString() magic method?", "back": "Defines how to convert an object to a string"},
  {"front": "What is PDO?", "back": "PHP Data Objects - a database abstraction layer"},
  {"front": "What is the purpose of the try-catch block in PHP?", "back": "Handles exceptions in code"},
  {"front": "What is the purpose of the finally block in exception handling?", "back": "Always executes regardless of whether an exception occurred"},
  {"front": "What is the difference between throw and throws in PHP?", "back": "throw is used to throw an exception; throws is not used in PHP"},
  {"front": "What is the purpose of a namespace in PHP?", "back": "To organize code and avoid naming conflicts"},
  {"front": "What is the function to check if a file exists in PHP?", "back": "file_exists()"},
  {"front": "What is the function to get the size of a file in PHP?", "back": "filesize()"},
  {"front": "What is the mode to open a file for reading only in PHP?", "back": "r"},
  {"front": "What is the mode to open a file for writing only and remove previous content?", "back": "w"},
  {"front": "What is the mode to open a file for appending in PHP?", "back": "a"},
  {"front": "What is the function to read a line from a file in PHP?", "back": "fgets()"},
  {"front": "What is the function to read a character from a file in PHP?", "back": "fgetc()"},
  {"front": "What is the function to read the entire file into a string?", "back": "file_get_contents()"},
  {"front": "What is the function to write to a file in PHP?", "back": "fwrite() or file_put_contents()"},
  {"front": "What is the function to delete a file in PHP?", "back": "unlink()"},
  {"front": "What is the function to create a directory in PHP?", "back": "mkdir()"},
  {"front": "What is the function to remove a directory in PHP?", "back": "rmdir()"},
  {"front": "What is the function to rename a file in PHP?", "back": "rename()"},
  {"front": "What is the purpose of the feof() function?", "back": "Checks if end of file has been reached"},
  {"front": "What is the purpose of the is_dir() function?", "back": "Checks if a path is a directory"},
  {"front": "What is JSON?", "back": "JavaScript Object Notation - a lightweight data interchange format"},
  {"front": "What is the function to encode a PHP array to JSON?", "back": "json_encode()"},
  {"front": "What is the function to decode JSON to a PHP array?", "back": "json_decode()"},
  {"front": "What is XML?", "back": "Extensible Markup Language"},
  {"front": "What is a valid XML document?", "back": "One that follows all XML rules and has a DTD"},
  {"front": "What is a well-formed XML document?", "back": "One that follows all XML syntax rules"},
  {"front": "What is a DTD?", "back": "Document Type Definition - defines structure of XML documents"},
  {"front": "What is XSL?", "back": "Extensible Stylesheet Language - for transforming XML"},
  {"front": "What is a framework in PHP?", "back": "A structured set of tools and libraries for building applications"},
  {"front": "What is Laravel?", "back": "A popular PHP web application framework using MVC architecture"},
  {"front": "What is Composer in PHP?", "back": "A dependency manager for PHP"},
  {"front": "What file does Composer use to define dependencies?", "back": "composer.json"},
  {"front": "What is the vendor directory in PHP projects?", "back": "Where Composer installs third-party libraries"},
  {"front": "What is the MVC pattern in web development?", "back": "Model-View-Controller - separates business logic from presentation"},
  {"front": "What is the Model in MVC?", "back": "Handles data and business logic"},
  {"front": "What is the View in MVC?", "back": "Handles UI presentation and display"},
  {"front": "What is the Controller in MVC?", "back": "Handles user input and coordinates Model and View"},
  {"front": "What is the purpose of Composer in PHP?", "back": "To manage project dependencies and autoloading"},
  {"front": "What is the purpose of the autoload feature in PHP?", "back": "Automatically loads classes when they are needed"},
  {"front": "What is a CMS?", "back": "Content Management System - for creating and managing digital content"},
  {"front": "What is a monolithic CMS?", "back": "A traditional CMS where back-end and front-end are tightly coupled"},
  {"front": "What is a headless CMS?", "back": "A CMS that stores content and delivers it via APIs without front-end rendering"},
  {"front": "What is WordPress?", "back": "A popular open-source CMS platform"},
  {"front": "What is the purpose of plugins in a CMS?", "back": "To extend the functionality of the CMS"},
  {"front": "What is XSS in web security?", "back": "Cross-Site Scripting - injecting malicious scripts into web pages"},
  {"front": "What is SQL Injection?", "back": "Injecting malicious SQL code into queries to manipulate the database"},
  {"front": "What is the best defense against SQL Injection?", "back": "Using prepared statements with bound parameters"},
  {"front": "What is CSRF?", "back": "Cross-Site Request Forgery - tricking users into performing unwanted actions"},
  {"front": "What is the purpose of CSRF tokens?", "back": "To validate that requests originate from the user's session"},
  {"front": "What is the purpose of CSP?", "back": "Content Security Policy - to restrict content sources and prevent XSS"}
];

const itpmCards = [
  {"front": "What is a project?", "back": "A temporary effort to create a unique product, service, or result"},
  {"front": "What is the difference between a project and operations?", "back": "Projects are temporary with a unique outcome; operations are ongoing and repetitive"},
  {"front": "What are the triple constraints of project management?", "back": "Scope, Time, and Cost"},
  {"front": "What is the project life cycle?", "back": "A series of phases a project passes through from initiation to closure"},
  {"front": "What are the five phases of a project life cycle?", "back": "Initiation, Planning, Execution, Monitoring & Controlling, Closure"},
  {"front": "What is a project charter?", "back": "A document that formally authorizes a project and gives the project manager authority"},
  {"front": "What is a stakeholder?", "back": "Any person or group involved in or affected by project activities"},
  {"front": "What is the difference between a project manager and a program manager?", "back": "Project manager leads a single project; program manager oversees multiple related projects"},
  {"front": "What is a deliverable?", "back": "A product produced as part of a project, such as software or planning documents"},
  {"front": "What is project scope?", "back": "All the work involved in creating the products of the project and the processes used"},
  {"front": "What is scope creep?", "back": "Uncontrolled changes or continuous growth in a project's scope"},
  {"front": "What is a Work Breakdown Structure (WBS)?", "back": "A deliverable-oriented grouping of work that defines the total scope of a project"},
  {"front": "What is a work package?", "back": "A task at the lowest level of the WBS"},
  {"front": "What is decomposition in WBS creation?", "back": "Subdividing project deliverables into smaller, more manageable pieces"},
  {"front": "What is a WBS dictionary?", "back": "A document that describes detailed information about each WBS item"},
  {"front": "What is a requirements traceability matrix?", "back": "A table linking requirements to their origin and status"},
  {"front": "What is the scope baseline?", "back": "The approved project scope statement, WBS, and WBS dictionary"},
  {"front": "What is project time management?", "back": "Processes required to ensure timely completion of a project"},
  {"front": "What is a dependency in project scheduling?", "back": "A logical relationship between project activities"},
  {"front": "What is a finish-to-start dependency?", "back": "Task B cannot start until Task A finishes"},
  {"front": "What is a start-to-start dependency?", "back": "Task B cannot start until Task A starts"},
  {"front": "What is a finish-to-finish dependency?", "back": "Task B cannot finish until Task A finishes"},
  {"front": "What is a project network diagram?", "back": "A schematic display of logical relationships among project activities"},
  {"front": "What is the critical path?", "back": "The longest path through the network diagram determining the earliest project completion"},
  {"front": "What is total float or slack?", "back": "The amount of time an activity can be delayed without delaying the project"},
  {"front": "What is free float?", "back": "The amount of time an activity can be delayed without delaying its successors"},
  {"front": "What is crashing in project management?", "back": "Adding resources to shorten task durations"},
  {"front": "What is fast tracking?", "back": "Performing activities in parallel to shorten the schedule"},
  {"front": "What is critical chain scheduling?", "back": "A scheduling method that considers limited resources and uses buffers"},
  {"front": "What is a project buffer in critical chain?", "back": "Additional time added before the project's due date"},
  {"front": "What is a feeding buffer?", "back": "Additional time added before tasks on the critical path"},
  {"front": "What is the cost of quality?", "back": "The cost of conformance plus the cost of nonconformance"},
  {"front": "What are prevention costs?", "back": "Costs invested to ensure conformance to requirements"},
  {"front": "What are appraisal costs?", "back": "Costs to identify defects after the fact"},
  {"front": "What are internal error costs?", "back": "Costs of rework before delivery to a customer"},
  {"front": "What are external error costs?", "back": "Costs of rework after delivery to a customer"},
  {"front": "What is ISO 9000?", "back": "An international set of standards for quality management"},
  {"front": "What is unit testing?", "back": "Testing each component to ensure it is defect-free"},
  {"front": "What is integration testing?", "back": "Testing functionally grouped components together"},
  {"front": "What is system testing?", "back": "Testing the entire system as one entity"},
  {"front": "What is user acceptance testing?", "back": "Testing performed by end users before accepting the system"},
  {"front": "What is a Gantt chart?", "back": "A bar chart displaying project schedule information"},
  {"front": "What is earned value management (EVM)?", "back": "A technique that integrates scope, time, and cost data"},
  {"front": "What is Planned Value (PV)?", "back": "The budgeted cost of work scheduled"},
  {"front": "What is Earned Value (EV)?", "back": "The budgeted cost of work actually performed"},
  {"front": "What is Actual Cost (AC)?", "back": "The total cost incurred for work performed"},
  {"front": "What is Cost Variance (CV)?", "back": "EV - AC (negative means over budget)"},
  {"front": "What is Schedule Variance (SV)?", "back": "EV - PV (negative means behind schedule)"},
  {"front": "What is Cost Performance Index (CPI)?", "back": "EV/AC (less than 1 means over budget)"},
  {"front": "What is Schedule Performance Index (SPI)?", "back": "EV/PV (less than 1 means behind schedule)"},
  {"front": "What is the estimate at completion (EAC) formula?", "back": "BAC / CPI"},
  {"front": "What is project risk management?", "back": "Systematic process of identifying, analyzing, and responding to project risks"},
  {"front": "What is risk utility?", "back": "The amount of satisfaction from a potential payoff"},
  {"front": "What is a risk-averse person?", "back": "Someone who prefers lower risk with lower returns"},
  {"front": "What is risk identification?", "back": "Determining which risks are likely to affect a project"},
  {"front": "What is qualitative risk analysis?", "back": "Characterizing and prioritizing risks based on probability and impact"},
  {"front": "What is quantitative risk analysis?", "back": "Measuring the probability and consequences of risks numerically"},
  {"front": "What is a probability/impact matrix?", "back": "A tool for assessing risk priority based on probability and impact"},
  {"front": "What is Top 10 Risk Item Tracking?", "back": "A tool for maintaining awareness of key risks over time"},
  {"front": "What is a decision tree?", "back": "A diagramming method used to select the best course of action under uncertainty"},
  {"front": "What is Expected Monetary Value (EMV)?", "back": "The sum of each outcome's probability multiplied by its monetary value"},
  {"front": "What is risk avoidance?", "back": "Eliminating a threat by eliminating its causes"},
  {"front": "What is risk mitigation?", "back": "Reducing the impact or probability of a risk event"},
  {"front": "What is risk transference?", "back": "Shifting the consequence of a risk to a third party"},
  {"front": "What is project communications management?", "back": "Ensuring timely and appropriate generation, collection, and distribution of project information"},
  {"front": "What is a communications management plan?", "back": "A document that guides project communications"},
  {"front": "What is the formula for communication channels?", "back": "n(n-1)/2 where n is the number of people"},
  {"front": "What is a status report?", "back": "A report describing where the project stands at a specific point in time"},
  {"front": "What is a progress report?", "back": "A report describing what the project team has accomplished during a certain period"},
  {"front": "What is the confronting conflict resolution style?", "back": "Directly facing and solving the conflict"},
  {"front": "What is the compromising conflict resolution style?", "back": "A give-and-take approach to reach a solution"},
  {"front": "What is the smoothing conflict resolution style?", "back": "De-emphasizing differences and emphasizing areas of agreement"},
  {"front": "What is the forcing conflict resolution style?", "back": "A win-lose approach using power to impose a solution"},
  {"front": "What is project procurement management?", "back": "Acquiring goods and services from outside the performing organization"},
  {"front": "What is a make-or-buy analysis?", "back": "Determining whether to produce or purchase a product or service"},
  {"front": "What is a fixed-price contract?", "back": "A contract with a fixed total price for well-defined products"},
  {"front": "What is a cost-reimbursable contract?", "back": "A contract where the buyer pays the seller's direct and indirect costs"},
  {"front": "What is a time and material contract?", "back": "A hybrid contract that combines fixed-price and cost-reimbursable elements"},
  {"front": "What is a Statement of Work (SOW)?", "back": "A description of the work required for a procurement"},
  {"front": "What is a Request for Proposal (RFP)?", "back": "A document used to solicit proposals from prospective sellers"},
  {"front": "What is a Request for Quote (RFQ)?", "back": "A document used to solicit quotes or bids from suppliers"},
  {"front": "What is a proposal?", "back": "A document prepared by a seller when there are different approaches for meeting buyer needs"},
  {"front": "What is the Delphi technique?", "back": "A panel of experts used for risk identification"},
  {"front": "What is Monte Carlo analysis?", "back": "A simulation technique that provides a statistical distribution of project outcomes"},
  {"front": "What is Maslow's Hierarchy of Needs?", "back": "A theory that human needs are arranged in a hierarchy"},
  {"front": "What is Theory X?", "back": "The assumption that workers dislike work and need to be controlled"},
  {"front": "What is Theory Y?", "back": "The assumption that workers find work natural and seek responsibility"},
  {"front": "What is a Responsibility Assignment Matrix (RAM)?", "back": "A chart that shows who is responsible for what work"},
  {"front": "What is resource loading?", "back": "The amount of resources an existing schedule requires during specific time periods"},
  {"front": "What is resource leveling?", "back": "A technique for resolving resource conflicts by delaying tasks"},
  {"front": "What is coercive power?", "back": "Power based on the ability to punish"},
  {"front": "What is expert power?", "back": "Power based on specialized knowledge or skills"},
  {"front": "What is referent power?", "back": "Power based on charisma and interpersonal relationships"},
  {"front": "What is legitimate power?", "back": "Power based on an organizational position or authority"},
  {"front": "What is the difference between a project and a program?", "back": "A project is a single endeavor; a program is a group of related projects"},
  {"front": "What is project portfolio management?", "back": "Grouping projects and programs to achieve strategic business goals"},
  {"front": "What is the purpose of a lessons learned session?", "back": "To document what went well and what went wrong for future projects"}
];

const sadCards = [
  {"front": "What does OOAD stand for?", "back": "Object-Oriented Analysis and Design"},
  {"front": "What is the difference between OOA and OOD?", "back": "OOA finds business objects; OOD defines how software objects collaborate"},
  {"front": "What is a class in OO?", "back": "A specification of structures, behavior, and inheritance for objects"},
  {"front": "What is an object?", "back": "An instance of a class with state and behavior"},
  {"front": "What is encapsulation in OO?", "back": "Hiding internal data and procedures, providing an interface"},
  {"front": "What is inheritance?", "back": "A relationship where one class is the parent of another, allowing reuse"},
  {"front": "What is polymorphism?", "back": "The ability of objects to respond to the same message in different ways"},
  {"front": "What is a message in OO?", "back": "A request sent to an object to perform an operation"},
  {"front": "What is a method in OO?", "back": "A procedure that implements the behavior of an object"},
  {"front": "What is information hiding?", "back": "Concealing internal details and revealing as little as possible about inner workings"},
  {"front": "What is a use case?", "back": "A set of actions performed by a system for a specific goal"},
  {"front": "What is a scenario in requirements?", "back": "A narrative description of what people do when using a system"},
  {"front": "What is an actor in UML?", "back": "An entity that interacts with the system"},
  {"front": "What is the difference between functional and non-functional requirements?", "back": "Functional describes what the system does; non-functional describes quality attributes"},
  {"front": "What is requirements elicitation?", "back": "Gathering information about stakeholder needs and expectations"},
  {"front": "What is requirements specification?", "back": "Documenting requirements in a clear, consistent, and unambiguous manner"},
  {"front": "What is requirements validation?", "back": "Checking that requirements are correct, complete, consistent, and realistic"},
  {"front": "What is requirements verification?", "back": "Ensuring software correctly implements specific functions"},
  {"front": "What is a feasibility study?", "back": "Analyzing technical, operational, economic, and legal aspects of a project"},
  {"front": "What is the unified approach (UA)?", "back": "A methodology combining Booch, Rumbaugh, and Jacobson with UML"},
  {"front": "What is UML?", "back": "Unified Modeling Language - a set of notations for modeling applications"},
  {"front": "What are the two orthogonal views of software?", "back": "Traditional (algorithm + data) and Object-Oriented"},
  {"front": "What is a class diagram?", "back": "A diagram showing classes, attributes, and relationships"},
  {"front": "What is a sequence diagram?", "back": "A diagram showing object interactions over time"},
  {"front": "What is a state machine diagram?", "back": "A diagram showing permitted states and transitions of an object"},
  {"front": "What is an activity diagram?", "back": "A diagram showing workflows and control flow"},
  {"front": "What is a component diagram?", "back": "A diagram showing how components are wired together"},
  {"front": "What is a deployment diagram?", "back": "A diagram showing the physical deployment of artifacts"},
  {"front": "What is an object diagram?", "back": "An instance of a class diagram at a specific point in time"},
  {"front": "What is a package diagram?", "back": "A diagram showing packages and their dependencies"},
  {"front": "What is a profile diagram?", "back": "A diagram for creating domain-specific stereotypes"},
  {"front": "What is a communication diagram?", "back": "A diagram showing object collaboration focused on relationships rather than time"},
  {"front": "What is an interaction overview diagram?", "back": "A diagram showing the flow of control of interactions"},
  {"front": "What is a timing diagram?", "back": "A diagram showing object behavior over a period of time"},
  {"front": "What is a use case diagram?", "back": "A diagram showing actors and their use cases"},
  {"front": "What is an entity object?", "back": "An object representing persistent information tracked by the system"},
  {"front": "What is a boundary object?", "back": "An object representing the interface between actors and the system"},
  {"front": "What is a control object?", "back": "An object coordinating boundary and entity objects for a use case"},
  {"front": "What is a robustness diagram?", "back": "A diagram visualizing relations between entities, controls, boundaries, and actors"},
  {"front": "What is a transformation in mapping models to code?", "back": "An operation that improves one aspect of a model while preserving other properties"},
  {"front": "What is refactoring?", "back": "A transformation of source code that improves readability without changing behavior"},
  {"front": "What is forward engineering?", "back": "Producing source code from model elements"},
  {"front": "What is reverse engineering?", "back": "Producing model elements from source code"},
  {"front": "What is a fault in testing?", "back": "A design or coding mistake that may cause abnormal behavior"},
  {"front": "What is a failure in testing?", "back": "A deviation between specification and actual behavior"},
  {"front": "What is a test case?", "back": "A set of inputs and expected results to exercise a test component"},
  {"front": "What is a test stub?", "back": "A partial implementation of components on which the tested component depends"},
  {"front": "What is a test driver?", "back": "A partial implementation that depends on the test component"},
  {"front": "What is black box testing?", "back": "Testing based on inputs and outputs without knowing internal logic"},
  {"front": "What is white box testing?", "back": "Testing based on specific logic and internal structures"},
  {"front": "What is top-down testing?", "back": "Testing that starts with main logic and proceeds to details"},
  {"front": "What is bottom-up testing?", "back": "Testing that starts with details and progressively aggregates"},
  {"front": "What is unit testing?", "back": "Testing individual components of a system"},
  {"front": "What is integration testing?", "back": "Testing functionally grouped components together"},
  {"front": "What is functional testing?", "back": "Testing differences between use case model and system"},
  {"front": "What is performance testing?", "back": "Testing differences between nonfunctional requirements and actual performance"},
  {"front": "What is reliability in software?", "back": "Probability that a system will not fail under specified conditions"},
  {"front": "What is an erroneous state?", "back": "A manifestation of a fault during system execution"},
  {"front": "What is statement testing coverage?", "back": "Testing every statement in an object's method at least once"},
  {"front": "What is branch testing coverage?", "back": "Executing every branch alternative at least once"},
  {"front": "What is path testing?", "back": "Ensuring each path in a method is executed at least once"},
  {"front": "What is coupling in software design?", "back": "A measure of how closely connected different modules are"},
  {"front": "What is cohesion in software design?", "back": "A measure of how functionally related elements within a module are"},
  {"front": "What is functional cohesion?", "back": "The highest level of cohesion where elements perform a single task"},
  {"front": "What is coincidental cohesion?", "back": "The lowest level of cohesion with unrelated elements"},
  {"front": "What is structural design approach?", "back": "Breaking down problems into well-organized elements"},
  {"front": "What is function-oriented design?", "back": "Dividing the system into subsystems called functions"},
  {"front": "What is the System Design Document (SDD)?", "back": "A document describing design goals, subsystem decomposition, and architecture"},
  {"front": "What is the Requirements Analysis Document template?", "back": "A document describing system requirements, use cases, and models"},
  {"front": "What is an off-the-shelf component?", "back": "A pre-existing software component used in system design"},
  {"front": "What is a transformation in the software process?", "back": "Each phase where output of one becomes input to the next"},
  {"front": "What is the waterfall approach?", "back": "A sequential software development process"},
  {"front": "What is prototyping in requirements elicitation?", "back": "Creating a working model to gather feedback and validate requirements"},
  {"front": "What is the Delphi technique?", "back": "A panel of experts used for requirements elicitation"},
  {"front": "What is the difference between a stereotype and a profile in UML?", "back": "A stereotype extends UML elements; a profile defines a set of stereotypes"},
  {"front": "What is a qualifier in UML?", "back": "An attribute that distinguishes objects in an association"},
  {"front": "What is a composition relationship?", "back": "A strong form of aggregation where parts cannot exist without the whole"},
  {"front": "What is an aggregation relationship?", "back": "A whole-part relationship where parts can exist independently"},
  {"front": "What is a dependency relationship in UML?", "back": "A relationship where change in one element affects another"},
  {"front": "What is a generalization relationship?", "back": "A relationship connecting a specialized element with a generalized one"},
  {"front": "What is a realization relationship?", "back": "A relationship where one element implements a responsibility of another"},
  {"front": "What is a use case realization?", "back": "The mapping from use cases to objects"},
  {"front": "What is the purpose of a glossary in requirements?", "back": "To define terms used in the requirements document"},
  {"front": "What is traceability in requirements?", "back": "The ability to trace system components back to requirements"},
  {"front": "What is a constraint in requirements?", "back": "A limitation or restriction imposed by the client or environment"},
  {"front": "What is a pseudo requirement?", "back": "Another term for a constraint in requirements"},
  {"front": "What is the difference between verification and validation?", "back": "Verification checks correctness of implementation; validation checks customer satisfaction"},
  {"front": "What is an analysis model?", "back": "A formal or semi-formal model describing the system from the developer's view"},
  {"front": "What is a requirements specification document?", "back": "A document describing system requirements in detail"},
  {"front": "What is a quality requirement?", "back": "A nonfunctional requirement describing attributes like usability, reliability, and performance"},
  {"front": "What is a robustness requirement?", "back": "The ability to maintain function even with invalid inputs or environmental changes"},
  {"front": "What is the Availability of a system?", "back": "The ratio of expected uptime to aggregate of up and down time"},
  {"front": "What is a system model in requirements?", "back": "A representation of system structure and behavior"},
  {"front": "What is a data dictionary?", "back": "A description of data elements used in the system"},
  {"front": "What is an interface in system design?", "back": "The shared boundary across which components exchange information"},
  {"front": "What is modularization in software engineering?", "back": "Dividing a software system into multiple independent modules"},
  {"front": "What is the purpose of a System Design Document?", "back": "To define interfaces between development teams and document architecture decisions"},
  {"front": "What is an Actor in use case modeling?", "back": "A role played by a user or external system interacting with the system"},
  {"front": "What is the difference between association and aggregation?", "back": "Association is a general relationship; aggregation is a whole-part relationship"}
];

const snaCards = [
  {"front": "What is a workgroup in Windows networking?", "back": "A collection of computers on a LAN that share resources as equals"},
  {"front": "What is the difference between a workgroup and a domain?", "back": "Workgroup uses peer-to-peer; domain uses centralized control with a Domain Controller"},
  {"front": "What is a Domain Controller?", "back": "A server that responds to authentication requests and verifies users on a network"},
  {"front": "What is Active Directory?", "back": "A directory service that stores domain database objects, attributes, and schema"},
  {"front": "What is the difference between a domain tree and a forest?", "back": "A tree is a hierarchy of domains; a forest is a collection of domain trees"},
  {"front": "What is a transitive trust in Active Directory?", "back": "A trust relationship that flows through a hierarchy of domains"},
  {"front": "What is a namespace in system administration?", "back": "A system for naming resources to avoid collisions and ensure unique identification"},
  {"front": "What does DNS stand for and what does it do?", "back": "Domain Name System - resolves hostnames to IP addresses"},
  {"front": "What are the two types of top-level domains?", "back": "gTLDs (generic) and ccTLDs (country code)"},
  {"front": "What is a recursive DNS query?", "back": "A query where the server does all the work to resolve the name"},
  {"front": "What is an authoritative DNS server?", "back": "A server that has the original data for a zone"},
  {"front": "What is the difference between a recursive and an authoritative DNS server?", "back": "Recursive servers do lookups; authoritative servers hold the actual zone data"},
  {"front": "What is DHCP and its primary purpose?", "back": "Dynamic Host Configuration Protocol - automatically assigns IP addresses"},
  {"front": "What are the four steps of DHCP lease acquisition?", "back": "Discover, Offer, Request, Acknowledgment"},
  {"front": "What is APIPA?", "back": "Automatic Private IP Addressing - used when DHCP is unavailable"},
  {"front": "What port does HTTP use?", "back": "Port 80"},
  {"front": "What is the difference between a web server and a web browser?", "back": "Web server hosts content; web browser requests and displays content"},
  {"front": "What are the three phases of email transfer?", "back": "Handshaking, message transfer, and closure"},
  {"front": "What is the difference between SMTP and POP3?", "back": "SMTP is for sending (push); POP3 is for receiving (pull)"},
  {"front": "What is Samba used for in Linux?", "back": "Sharing files and printers with Windows systems using SMB/CIFS"},
  {"front": "What is the Linux kernel?", "back": "The core of the Linux operating system managing hardware and processes"},
  {"front": "What is the root directory in Linux?", "back": "/"},
  {"front": "What are the three permission types in Linux?", "back": "Read, Write, Execute"},
  {"front": "What are the three permission groups in Linux?", "back": "Owner, Group, Others"},
  {"front": "What does the command `chmod 755` do?", "back": "Sets rwx for owner, rx for group and others"},
  {"front": "What does `chown user:group file` do?", "back": "Changes the owner and group of a file"},
  {"front": "What is the difference between `/etc/passwd` and `/etc/shadow`?", "back": "Passwd stores user info; shadow stores hashed passwords securely"},
  {"front": "What is PAM in Linux?", "back": "Pluggable Authentication Modules - allows reconfiguring authentication"},
  {"front": "What is a loopback device in Linux?", "back": "A device that encrypts/decrypts data between the file system and processes"},
  {"front": "What is SELinux?", "back": "Security-Enhanced Linux - provides mandatory access control"},
  {"front": "What is the difference between ACL and MAC permissions?", "back": "ACL is discretionary; MAC is mandatory and more restrictive"},
  {"front": "What is IPTables in Linux?", "back": "A firewall tool for controlling network traffic"},
  {"front": "What does the `ps` command do?", "back": "Displays a snapshot of current processes"},
  {"front": "What does the `top` command do?", "back": "Continuously displays running processes in real-time"},
  {"front": "What is the difference between `kill` and `kill -9`?", "back": "Kill sends a termination signal; kill -9 forcefully kills a process"},
  {"front": "What does the `ls -l` command display?", "back": "Detailed file listing with permissions, ownership, and size"},
  {"front": "What is the difference between a dedicated and non-dedicated file server?", "back": "Dedicated serves only files; non-dedicated serves multiple purposes"},
  {"front": "What is bandwidth?", "back": "The maximum amount of data transmitted over a network in a given time"},
  {"front": "What is remote administration?", "back": "Managing a computer or network from a remote location"},
  {"front": "What is RAID?", "back": "Redundant Array of Independent Disks - for performance and redundancy"},
  {"front": "What is RAID 0?", "back": "Striping without redundancy - improves performance only"},
  {"front": "What is RAID 1?", "back": "Mirroring - provides redundancy without striping"},
  {"front": "What is RAID 5?", "back": "Striping with parity - requires at least 3 drives"},
  {"front": "What is RAID 10?", "back": "Combines mirroring and striping - requires at least 4 drives"},
  {"front": "What is the difference between RAID 0 and RAID 1?", "back": "RAID 0 is striping; RAID 1 is mirroring"},
  {"front": "What is SCSI?", "back": "Small Computer Systems Interface - for connecting peripherals"},
  {"front": "What is system administration?", "back": "Modifying the system to bring it closer to the ideal state"},
  {"front": "What is system state S(t) in system administration?", "back": "The current configuration of a system at time t"},
  {"front": "What is the difference between a sysadmin in a small org vs a large org?", "back": "Small org: jack-of-all-trades; Large org: specialist roles"},
  {"front": "What are the principles of system administration?", "back": "Simplicity, Clarity, Generality, Automation, Communication, Basics First"},
  {"front": "What is the SAGE Code of Ethics?", "back": "A code of ethics for system administrators"},
  {"front": "What are the system administration maturity levels?", "back": "Ad Hoc, Repeatable, Defined, Managed, Optimized"},
  {"front": "What is LISA?", "back": "Large Installation System Administration - a USENIX conference"},
  {"front": "What is the difference between RHCE and MCSA?", "back": "RHCE is Red Hat certification; MCSA is Microsoft certification"},
  {"front": "What is a system resource?", "back": "A component like CPU, memory, disk, or network bandwidth"},
  {"front": "What is the purpose of resource monitoring?", "back": "To track usage and identify performance issues before they become critical"},
  {"front": "What does the `top` command in Linux monitor?", "back": "Real-time CPU and memory usage by processes"},
  {"front": "What is the difference between `top` and `htop`?", "back": "htop is a more advanced version with a graphical interface"},
  {"front": "What is disk queue length?", "back": "The number of outstanding read/write requests at a given time"},
  {"front": "What is the difference between a file server and a mail server?", "back": "File server stores files; mail server handles email"},
  {"front": "What is the difference between a web server and an application server?", "back": "Web server serves static content; application server handles dynamic logic"},
  {"front": "What is the difference between a firewall and an IDS?", "back": "Firewall blocks traffic; IDS detects intrusions"},
  {"front": "What is the difference between TCP and UDP?", "back": "TCP is connection-oriented; UDP is connectionless"},
  {"front": "What is the role of a system administrator?", "back": "To keep systems running efficiently and securely"},
  {"front": "What is a namespace policy?", "back": "A set of rules governing how names are chosen and managed"},
  {"front": "What is a flat namespace?", "back": "A namespace with no hierarchy and no duplicate names allowed"},
  {"front": "What is a hierarchical namespace?", "back": "A namespace organized as a tree with duplicate names in different branches"},
  {"front": "What is the difference between `ping` and `traceroute`?", "back": "Ping tests connectivity; traceroute shows the path taken"},
  {"front": "What is the purpose of `/etc/resolv.conf`?", "back": "Specifies DNS servers for name resolution"},
  {"front": "What is the purpose of `nslookup`?", "back": "To query DNS for name resolution information"},
  {"front": "What is a CNAME record in DNS?", "back": "Canonical Name - an alias for another domain name"},
  {"front": "What is an A record in DNS?", "back": "Maps a domain name to an IPv4 address"},
  {"front": "What is a PTR record in DNS?", "back": "Maps an IP address to a domain name"},
  {"front": "What is the difference between a forward and reverse DNS lookup?", "back": "Forward resolves name to IP; reverse resolves IP to name"},
  {"front": "What is a subnet mask?", "back": "Divides an IP address into network and host portions"},
  {"front": "What is the default subnet mask for Class C?", "back": "255.255.255.0"},
  {"front": "What is the loopback IP address?", "back": "127.0.0.1"},
  {"front": "What is the difference between IPv4 and IPv6?", "back": "IPv4 is 32-bit; IPv6 is 128-bit"},
  {"front": "What is the difference between a hub and a switch?", "back": "Hub broadcasts traffic; switch forwards based on MAC addresses"},
  {"front": "What is a router?", "back": "A device that forwards packets between different networks"},
  {"front": "What is a default gateway?", "back": "The router used when a destination is not on the local network"},
  {"front": "What is the difference between a static and dynamic IP address?", "back": "Static is fixed; dynamic is assigned by DHCP"},
  {"front": "What is VLAN?", "back": "Virtual LAN - a logical partition of a network"},
  {"front": "What is the purpose of a VLAN?", "back": "To contain broadcasts and group devices logically"},
  {"front": "What is a port in networking?", "back": "A logical endpoint for network communication"},
  {"front": "What is the well-known port range?", "back": "0-1023"},
  {"front": "What is the registered port range?", "back": "1024-49151"},
  {"front": "What is the dynamic/private port range?", "back": "49152-65535"},
  {"front": "What is a packet in networking?", "back": "A unit of data transmitted over a network"},
  {"front": "What is the difference between a packet and a frame?", "back": "Packet is at the network layer; frame is at the data link layer"},
  {"front": "What is the OSI model?", "back": "A seven-layer model for network communication"},
  {"front": "What are the seven layers of the OSI model?", "back": "Physical, Data Link, Network, Transport, Session, Presentation, Application"},
  {"front": "What is the difference between the OSI and TCP/IP models?", "back": "OSI has 7 layers; TCP/IP has 4 layers"},
  {"front": "What is NAT?", "back": "Network Address Translation - translates private to public addresses"},
  {"front": "What is the difference between NAT and PAT?", "back": "NAT maps IP to IP; PAT maps multiple IPs to one IP using ports"},
  {"front": "What is a proxy server?", "back": "An intermediary that processes client requests for security or caching"},
  {"front": "What is the difference between a forward and reverse proxy?", "back": "Forward proxy protects clients; reverse proxy protects servers"},
  {"front": "What is a VPN?", "back": "Virtual Private Network - creates a secure encrypted tunnel over a public network"},
  {"front": "What is the difference between a site-to-site and remote access VPN?", "back": "Site-to-site connects networks; remote access connects individual users"}
];

async function seedDeck(courseCode, courseTitleFallback, deckTitle, cards) {
  const courseRes = await pool.query(
    "SELECT id, title, code FROM courses WHERE code = $1 OR title ILIKE $2 LIMIT 1",
    [courseCode, `%${courseTitleFallback}%`]
  );

  let courseId;
  if (courseRes.rows.length > 0) {
    courseId = courseRes.rows[0].id;
    console.log(`✅ Found course: [${courseRes.rows[0].code}] ${courseRes.rows[0].title} (ID: ${courseId})`);
  } else {
    console.log(`⚠️ Course ${courseCode} not found in database.`);
    return;
  }

  // Check if deck exists
  const existingDeck = await pool.query(
    "SELECT id FROM flashcard_decks WHERE course_id = $1 AND is_public = TRUE",
    [courseId]
  );

  let deckId;
  if (existingDeck.rows.length > 0) {
    deckId = existingDeck.rows[0].id;
    console.log(`🔄 Updating existing public deck [${deckTitle}] (Deck ID: ${deckId})`);
    await pool.query(
      "UPDATE flashcard_decks SET title = $1, is_public = TRUE WHERE id = $2",
      [deckTitle, deckId]
    );
    await pool.query("DELETE FROM flashcards WHERE deck_id = $1", [deckId]);
  } else {
    const newDeck = await pool.query(
      "INSERT INTO flashcard_decks (user_id, course_id, title, is_public) VALUES (NULL, $1, $2, TRUE) RETURNING id",
      [courseId, deckTitle]
    );
    deckId = newDeck.rows[0].id;
    console.log(`✨ Created new public deck [${deckTitle}] (Deck ID: ${deckId})`);
  }

  // Batch insert cards in chunks of 25
  const chunkSize = 25;
  let totalInserted = 0;

  for (let i = 0; i < cards.length; i += chunkSize) {
    const chunk = cards.slice(i, i + chunkSize);
    const valueStrings = [];
    const values = [];

    chunk.forEach((card, idx) => {
      const offset = idx * 3;
      valueStrings.push(`($${offset + 1}, $${offset + 2}, $${offset + 3})`);
      values.push(deckId, card.front.trim(), card.back.trim());
    });

    const queryText = `INSERT INTO flashcards (deck_id, front, back) VALUES ${valueStrings.join(', ')}`;
    await pool.query(queryText, values);
    totalInserted += chunk.length;
  }

  console.log(`🎉 Seeded ${totalInserted} flashcards for [${deckTitle}]!`);
}

async function runSeed() {
  try {
    console.log('🚀 Starting Flashcards Seeder for NDC, IP2, ITPM, SAD, and SNA...');

    // 1. Network Devices and Configuration (NDC314)
    await seedDeck(
      'NDC314',
      'Network Devices',
      'NDC314: Network Devices and Configuration - Complete Flashcards (101 Questions)',
      ndcCards
    );

    // 2. Internet Programming II (IP2310)
    await seedDeck(
      'IP2310',
      'Internet Programming II',
      'IP2310: Internet Programming II - Complete Flashcards (97 Questions)',
      ip2Cards
    );

    // 3. IT Project Management (ITPM303)
    await seedDeck(
      'ITPM303',
      'Project Management',
      'ITPM303: IT Project Management - Complete Flashcards (98 Questions)',
      itpmCards
    );

    // 4. System Analysis and Design (SAD305)
    await seedDeck(
      'SAD305',
      'System Analysis',
      'SAD305: System Analysis and Design - Complete Flashcards (99 Questions)',
      sadCards
    );

    // 5. System and Network Administration (SNA313)
    await seedDeck(
      'SNA313',
      'System and Network Administration',
      'SNA313: System and Network Administration - Complete Flashcards (98 Questions)',
      snaCards
    );

    console.log('🏁 All 5 requested decks successfully seeded!');
  } catch (err) {
    console.error('❌ Error during seeding:', err);
  } finally {
    process.exit(0);
  }
}

runSeed();
